baseurl = "https://www.roccatello.it/"
title = "Eduard Roccatello's GIS blog"
copyright = "&copy; 2025"

theme = "eduard-v3"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableRobotsTXT = true

# Enable comments by entering your Disqus shortname
disqusShortname = ""

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Get last modified date for content from Git?
enableGitInfo = false

[outputs]
  home = [ "HTML", "RSS" ]
  section = [ "HTML", "RSS" ]

[minify]
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepQuotes = true
      keepWhitespace = false

[blackfriday]
  hrefTargetBlank = true
  fractions = true
  smartypants = true

[permalinks]
  'post' = '/:year/:month/:slug/'

[pagination]
  pagerSize = 10

[params]
  name = "Eduard Roccatello"
  role = ""
  organizations = [ { name = "3DGIS Chief Technical Officer", url = "https://www.3dgis.it" } ]

  gravatar = false  # Get your avatar from Gravatar.com? (true/false)
  avatar = "avatar.png"  # Specify an avatar image (in `static/img/` folder) or delete value to disable avatar.
  
  address = "Bergamo. Rovigo. Padova."

  map = 0
  map_api_key = ""
  latitude = "45.050801"
  longitude = "11.780133"
  zoom = 6

  # Description for social sharing and search engines. If undefined, author role is used in place.
  description = "Esperto di geoinformatica e software design. Faccio ricerca e sviluppo a 3DGIS. La mia mission è fornire strumenti per costruire un mondo migliore"
  sharing_image = "avatar.png"
  twitter = "edurocc"
  date_format = "2006-01-02"
  time_format = "15:04"

  # Show estimated reading time for posts?
  reading_time = true

  # Display comment count? Requires commenting to be enabled.
  comment_count = false

  # Display next/previous section pager?
  section_pager = true

  # Enable global LaTeX math rendering?
  #   If false, you can enable it locally on a per page basis.
  math = false

  highlight = true
  highlight_languages = []
  highlight_style = "github"

  sharing = true
  privacy_pack = true

  custom_css = []
  custom_js  = []

  publication_types = [
    'Uncategorized',  # 0
    'Conference paper',  # 1
    'Journal article',  # 2
    'Manuscript',  # 3
    'Report',  # 4
    'Book',  # 5
    'Book section'  # 6
  ]

  # Configuration of talk pages.
  [params.talks]
    # Show talk time?
    time = true

  # Configuration of publication pages.
  [params.publications]
    # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "January, 2006"

  # Configuration of project pages.
  [params.projects]
    # List publications and talks related to the project?
    list_children = true
    publication_format = 3

  [[params.social]]
    icon = "envelope"
    icon_pack = "fas"
    link = "mailto:eduard.roccatello@3dgis.it"
    text = "eduard.roccatello@3dgis.it"

  [[params.social]]
    icon = "github"
    icon_pack = "fab"
    link = "//github.com/mastershadow"
    text = "github.com/mastershadow"

[[menu.main]]
  name = "Tales from the GIS"
  url = "#mondogis"
  weight = 2

[[menu.main]]
  name = "Showcase"
  url = "#showcase"
  weight = 4

[[menu.main]]
  name = "Articles"
  url = "post"
  weight = 3
  
[[menu.main]]
  name = "About"
  url = "#aboutme"
  weight = 6

[[menu.main]]
  name = "Contacts"
  url = "#contacts"
  weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
