---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/post
  label: Post
  create: all
  match: "**/*"
- type: directory
  path: content/home
  label: Home
  create: all
  match: "**/*"
- type: directory
  path: content/project
  label: Project
  create: all
  match: "**/*"
- type: directory
  path: content/publication
  label: Publication
  create: all
  match: "**/*"
upload_dir: ''
public_path: https://res.cloudinary.com/roccatello/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":year/:filename/:filename:"
version: '0.52'
